apiVersion: v1
kind: Pod
metadata:
  name: node-express-sample
  namespace: default
  labels:
    name: node-express-sample
  
spec:
  containers:
  - name: node-express-sample
    image: gcr.io/master-dev-253408/node-express-sample:v2
    env:
      - name: APP_PORT
        value: "4000"
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: 250m
        memory: 512Mi
