apiVersion: v1
kind: Pod
metadata:
  name: node-express-sample
  namespace: default
  labels:
    name: node-express-sample
  
spec:
  containers:
  - name: node-express-sample
    image: tusharlt/tushar-lt:node-express-sample
    env:
      - name: APP_PORT
        value: "4000"
    resources:
      requests:
        cpu: 1
        memory: 512Mi
      limits:
        cpu: 1
        memory: 512Mi
